[[bliss]]
arch = "aarch64"
git-tree-sha1 = "059ae6b9be20cbe7de2aa74d48edfc808b5a5e8e"
os = "macos"

    [[bliss.download]]
    sha256 = "4462c74234cf77b5bf0bb9b107f4780ab3d8f1c6bbe2b21eb4ea5fbf25bffd7f"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.aarch64-apple-darwin.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "c308dac0f5878facd61c4302b136d54fd41336df"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "ba1b3f0568ec7604f69ff0b79cb076cb33c586d16fc5f13f484384f4063b5762"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.aarch64-linux-gnu.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "c686ec2bf45c71de646562953864de7682954774"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "b81ccb4d5736333b138ef4aa5ea74faffb178b9ba7760ce6c8bb30db8dff560c"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.aarch64-linux-musl.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e7ef55b6cd1e6a6da010922e2143c4154c8b194"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "f64ba4587c7b059dbe8cabc40516ae78faef5bf9de80f8dd5a58226d92e32bd2"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.armv6l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73091048162f98bce993c1ad17ff1dfdaabcadc5"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "4737536f5733cc9eaf6d01a0edc37d60e5b5b813a06d2d22dfd6e355dbd356b9"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.armv6l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "346b5ff9b0579efd7dc770151a7ac11683323fee"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "17c48f415df391aeb41519c633becf55217821b1d78324bb347e5bfc9a3c37e5"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.armv7l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd68d11e996e3ae48cf9800c191636c03f85796d"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "56eec73904acb86d38ded98e952bac227d9c750d2ffb39c2faf16a884eb9f45e"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.armv7l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "14aa8b84bc3227dd39622c510d398433c1ce585d"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "997d0929f5d09b058a6f72684a12167f1c79e1923d78fbab795fc0fb465ed473"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.i686-linux-gnu.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "2ea63a90e310e8f8140d4a5bd441fdd20e8ceda9"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "e8183f15acfa1dfbc1435dcb0164c4c30cbdfdc3b825567eb34aee7519715fff"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.i686-linux-musl.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "0b3ee9f5d8ac8181d4ce3bd54e5c2a1e6c00222b"
os = "windows"

    [[bliss.download]]
    sha256 = "31d7ffac33d6a07afe9614c3eacd170d8ca247ebb455e4228f956d1f96ace9cc"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.i686-w64-mingw32.tar.gz"
[[bliss]]
arch = "powerpc64le"
git-tree-sha1 = "e91c30392481a9f06cb23b373a7ab516ef726017"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "9d7b7b0f1af5f86a76193cf42f80757d9ca7f8587f7e15e154b32ddf5eb80e9b"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.powerpc64le-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "ca6e825ce745e60e7faebd134d6ad7224dc07f5b"
os = "macos"

    [[bliss.download]]
    sha256 = "436d977a4327e2c9a0fba07a8e1ed01aaeaa80366e09a1d740e349d57eb1033f"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.x86_64-apple-darwin.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "067f3131004b5dd885d240d4000e90fbb4a93e47"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "b0401f313adadb36872a1ea17fd0075afc9dbfdfba3cb1a28e6564922d78474c"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.x86_64-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "c3f2cc86c788788ba94a8ca4b4d82cfe69ab07c4"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "067a47145633f463b1543256dc007a084357c3eae2ba837fb2aaba038bb7f4a3"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.x86_64-linux-musl.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "dbf86df8f7dd2399815fbe87e0a3b03750d915a5"
os = "freebsd"

    [[bliss.download]]
    sha256 = "1885b3ba8cf617d6a02ea292c7209d9d3e079e8dff641ccc2f2e580992d92476"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.x86_64-unknown-freebsd.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "43727792b4f3406dd3f063d27f58f87e4cc5779a"
os = "windows"

    [[bliss.download]]
    sha256 = "b3ae6d97c47f2b0273324d864719a71facabccb0e92ac2b80786e9f912f5c441"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.73.1+0/bliss.v0.73.1.x86_64-w64-mingw32.tar.gz"
