[[bliss]]
arch = "aarch64"
git-tree-sha1 = "ab254538401bbb5724ef83ea5e685d8dac9d39ff"
os = "macos"

    [[bliss.download]]
    sha256 = "2ca95ff4065c3ea541a1ae1df428437ad85ee88b830a8fd9ef5299040693fc46"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.aarch64-apple-darwin.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "9c503ed2166d6513c0e82b94a6e8bfe6e4f1a4ac"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "3010b13d2f55956bff48ab8e7ae039ef5e4c3282d2207192711a994d19679d2a"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.aarch64-linux-gnu.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "3c42218a3085871b3f60468b810cad97bccd7ac1"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "53f18488de8c03afb177acb2ff0e391198d5e3094a169d72e9ad573b29480664"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.aarch64-linux-musl.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3ec1f0bf4be3c58dac000361cb43adee9be4972"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "c5e3095b5f9bfb158a8642fc900743b65b1330cb9f0d7469f716346d49664639"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.armv6l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b6fd8fbe7c416aca6d7a6464be3fe9779ec871d"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "0e56d1fbd754e8877f37655505109a5d29e918f1bc5bd3f907bc0b76083ae2cf"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.armv6l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c5325bf3b68ffce3100d32b58061949afa92ca17"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "85f31740bba612c2311c115a3d2ff24d37ae3bd01ced6b6b4dc7b886a390f12e"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.armv7l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f96bc56632e3db0f107ce80ea7f289218aece7eb"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "1607dd7d38a689ef3034747e042166757dfd4ae02df4912f465c01fec24de8fd"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.armv7l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "9db73c251ecb0793a477b50f1913d48abe181f78"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "a4cb1000fecbe720492345686f1954afc72027043d230061842c2d14e7b9cbf8"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.i686-linux-gnu.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "682c0d491a1cb6d49e48b4a24e9db1cff53e85cf"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "9035545c01717e7f86ca842bb0739a59bbfddd8e2d2deb13047936693cb1ad49"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.i686-linux-musl.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "5148400dbc091d00b56cea1a0102340fa74bfae1"
os = "windows"

    [[bliss.download]]
    sha256 = "4a28e571cfaada138ca13d33c53737b2690d9a5a1eb35efd01ad6dd1c0a7489b"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.i686-w64-mingw32.tar.gz"
[[bliss]]
arch = "powerpc64le"
git-tree-sha1 = "ea85a308cb67cdefecd6e5739db8ea2adaf901b9"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "611199cface8f1499f6e0b2b6849d51a3ef532b17f5b833b161b8a7007aad343"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.powerpc64le-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "e8e14099d396b38630b2555b46448e3e1c7c476a"
os = "macos"

    [[bliss.download]]
    sha256 = "65e9676683b55eb6fde30c1247c24f52945824757b2ec1f2d1c39b72d8194dd6"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.x86_64-apple-darwin.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "d6c4a695f096a6f1ce34871131025d421d789a46"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "4f0c6f323d7d4dee1fc4c7dbfe9ddaa5239ea610b3f835695350e6f9d9d0ac23"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.x86_64-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "c9ca9395617203bc78639f8ab8276e478a85d520"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "4dfb5738dbeb6839a25b68eb51bc2b32c9524c60433e144790ef55115fc54be0"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.x86_64-linux-musl.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "dc49e35fc026b4c83e224dcda90559d32b38c5d4"
os = "freebsd"

    [[bliss.download]]
    sha256 = "692823c70cba57e5329e9be2e33d3a445c5ebc708728a5e67780d0d09e15a157"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.x86_64-unknown-freebsd.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "79b5388cec65ac61c6997bdc8ed299378b480c2b"
os = "windows"

    [[bliss.download]]
    sha256 = "4c9544ae2b5beaa72eafaeee24707fb3743fa6e9d2098342b0fdf62cd231d558"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+1/bliss.v0.77.0.x86_64-w64-mingw32.tar.gz"
