[[bliss]]
arch = "aarch64"
git-tree-sha1 = "8f00b9687934ffb56ded6cc748d002c4f52a7911"
os = "macos"

    [[bliss.download]]
    sha256 = "9953a951c475e3147bc88d6c206476dfd8155d6f491b7c6097f940af28b46d36"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.aarch64-apple-darwin.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "d74a3fcb02208aca6b81168383671fa19b0ae83e"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "34481ffe5c6819e751953a7f49f65487b72a293049328a5348a74f6640a23380"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.aarch64-linux-gnu.tar.gz"
[[bliss]]
arch = "aarch64"
git-tree-sha1 = "dedf3d932df11588b583be39774f0214e740099d"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "a33391882507958af42c00c7c32687ab5723c395cab7b7da1f407b3cfb881e01"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.aarch64-linux-musl.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6fb47aa815c40b759f64c401ab22a6f9df33ec8"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "889697e8c0d9cec2edc27eda794d38124270bbd3ad99910844b37d6508fb7623"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.armv6l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de69f895fdb382e6533e114875cada91273e7d52"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "78a83c900791d1b8ba0bd185d45b1800d795d7088ed3bca7f4db937025dfb8cc"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.armv6l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "885e24cfd721900e4d7531c688286392fe092ea3"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "13cd7a6e5be6566af4edfa80cd05abb458fe223b65149fc22856e691de0547e9"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.armv7l-linux-gnueabihf.tar.gz"
[[bliss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2af8ba741b038422843c93ebd88d0117218757e9"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "db3cde694327b6ddef84430eb90eb7f974f73ed1eac883981141ae0e7560eda9"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.armv7l-linux-musleabihf.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "2700f6023c11b840d24823cd6b50ab3ff561ca41"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "1bed44f5dd6f93aea68cb029d45f54dde92f3e94b48fd9652f217d513d6feecb"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.i686-linux-gnu.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "55d3f81b045bbc14c6011d4ba2f66f5827bfd2c4"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "23efc0f80cd7db7fca998bb5111be6b3b86046db34919c64822d445f4694ea93"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.i686-linux-musl.tar.gz"
[[bliss]]
arch = "i686"
git-tree-sha1 = "f8b0f9d9795acc7c1213f121a4c87dc02a89875a"
os = "windows"

    [[bliss.download]]
    sha256 = "36315223bd91f227c02eedd7a6d729d97df2b8016865edba49d9793250fa2875"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.i686-w64-mingw32.tar.gz"
[[bliss]]
arch = "powerpc64le"
git-tree-sha1 = "518ceb33e92207507a37891025f61d3e4545c980"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "cf5382f4255e41e5085e2426894653cb0f2bc08686b6c150e84645ebad4bb776"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.powerpc64le-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "e39ec13f769319fed9a38cceaa40d79f5f033df7"
os = "macos"

    [[bliss.download]]
    sha256 = "c412031c71aa22b89930722684f6e2823a434c9fd07f7334716b01869562d138"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.x86_64-apple-darwin.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "cc3ea7806b600c67b57b9b90855d6c58767ba596"
libc = "glibc"
os = "linux"

    [[bliss.download]]
    sha256 = "39e7b04849a3d9bae79520be22e039747c8f345fcca2fd33ad4db7b89e0c218f"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.x86_64-linux-gnu.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "a0948edb6f6b3d410b3ac55e9a56e185cec474c0"
libc = "musl"
os = "linux"

    [[bliss.download]]
    sha256 = "f81af8ace3646fb6dd7e847548049fb0f8ac11d12aa74bacbf63de96bb440bb1"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.x86_64-linux-musl.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "6f5e4e1c99a08f7103d0e36c4999feba799ffd26"
os = "freebsd"

    [[bliss.download]]
    sha256 = "b708f36a0a372131835703ef4163a74b6efab38e9779642243d60cde77d15962"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.x86_64-unknown-freebsd.tar.gz"
[[bliss]]
arch = "x86_64"
git-tree-sha1 = "1b2406d0b568b8b2088a45cfeb7e5ba19ff3a37a"
os = "windows"

    [[bliss.download]]
    sha256 = "2c72dc5a7c45129dd8bbd364df91049987254069eda108355f5f01be94cf3c36"
    url = "https://github.com/JuliaBinaryWrappers/bliss_jll.jl/releases/download/bliss-v0.77.0+0/bliss.v0.77.0.x86_64-w64-mingw32.tar.gz"
