# Autogenerated wrapper script for bliss_jll for x86_64-w64-mingw32
export bliss, libbliss

using GMP_jll
JLLWrappers.@generate_wrapper_header("bliss")
JLLWrappers.@declare_library_product(libbliss, "libbliss.dll")
JLLWrappers.@declare_executable_product(bliss)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libbliss,
        "bin\\libbliss.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        bliss,
        "bin\\bliss.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
